version: 'version'

services:
  database_sgs:
    image: postgres
    container_name: database_sgs
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=Lc_150595
      - POSTGRES_DB=sgs
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: sgs
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_sgs
    depends_on:
      - database_sgs

volumes: 
    pgdata:
        driver: local
    
